# Generated by Django 4.2.7 on 2023-11-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro_humedad',
            fields=[
                ('idHumedad', models.AutoField(primary_key=True, serialize=False)),
                ('prc_humedad', models.IntegerField()),
                ('fecha_obtencion', models.DateField()),
            ],
        ),
    ]
