# Generated by Django 4.2.7 on 2023-11-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TerraSenseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_humedad',
            name='idHumedad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
